### ISSUE TITLE
The latest version seems to consistently overshoot the size limit.

### ISSUE THREAD

**Issue by SamuelBucher** [argorar/WebMConverter#63]
![image](https://github.com/argorar/WebMConverter/assets/56469863/0afe6bd2-dc56-4342-89ca-407f296feb8c)

This was for a trim + resize + decrease FPS, but even a simple trim job can no longer fit into the set range unless it's very short. I don't remember past version struggling with this.

**Comment by argorar** [comment]
Do another without decrease FPS and show the arguments next time.

**Comment by argorar** [comment]
Did a few test with 4k sources and converted fine under file size. Updated Radeon recently?
Upload a test field as said [here](https://github.com/argorar/WebMConverter/blob/master/README.md#issues).

**Comment by SamuelBucher** [comment]
I did, yes. I update Radeon regularly. By test video, you mean the output of the program, right?

**Comment by argorar** [comment]
No, I mean a video source made with radeon to do 8 seconds output example to test.

**Comment by SamuelBucher** [comment]
Okay, here is the video that made me open this issue.
https://litter.catbox.moe/rimrn2.mp4
Just be wary of the fact that this link expires in 3 days.

**Comment by argorar** [comment]
Using test file:
- 8 seconds trim, no crop, no resize, no reduce fraps, using VP9
![imagen](https://github.com/argorar/WebMConverter/assets/9936760/9d6d823a-9a11-4ab3-87b6-d1a9a7664038)
- 32 second trim, no crop, resize to 1280, reduce fraps to 30, using VP9
![imagen](https://github.com/argorar/WebMConverter/assets/9936760/6e7d1fb7-83db-43b8-96fc-08fb144d8c1c)

In both cases result output is under 4 MB. Notice that I am using high quality mode. If you have WebMConverter since time ago I recommend to download from releases the latest binaries to use latest ffmpeg and other libraries. The feature to target a filesize isn't recommended to long videos +30 seconds for obvious reasons that is more hard to stay under the size.

The issue will be closed.

**Comment by SamuelBucher** [comment]
Your program never really struggled to fit in the size restraint in the past, but now that I updated it like you said, it's back to not struggling with it. Thank you, issue solved and rightfully closed.
