### ISSUE TITLE
Could you consider adding an automatic rename function?

### ISSUE THREAD

**Issue by kirbco** [argorar/WebMConverter#73]
Like when you add a file with the same name to a folder in Windows and it gives you the option to add a (1) or something. I would really appreciate an automatic file renamer when you're saving to the same location so when I'm doing multiple clips from one source I don't have to constantly save somewhere else or change the name every time so I don't accidentally rewrite the previous one. 

Would also be extremely helpful if you'd add an option to remove a trim from Multi-Trim. There's been more than a few times where I'll want to remove a single trim but keep the others and the only option is start over because you can only add and not remove. 

... would also be cool if you could change the rate of a single trim in Multi-Trim. 

Sorry for asking for so much.

**Comment by argorar** [comment]
- Use this beautiful button in the middle, will add -n for a next file
![imagen](https://github.com/argorar/WebMConverter/assets/9936760/fb8f9af0-e91c-4c07-9e37-01fba70eea9b)
- Added
- Not possible since it will change frame rate and mess the whole process

**Comment by fhtdtdj** [comment]
"There's been more than a few times where I'll want to remove a single trim but keep the others and the only option is start over because you can only add and not remove."

You could just press Delete with your keyboard to remove a segment before.

Minor nitpick/suggestion: Please don't add "Remove" below "Cancel" and "Confirm". Users are used to clicking on the bottom button to Confirm/OK, this could lead to deleting a segment by mistake. Suggestion: place it above or below add, above cancel/confirm.

**Comment by argorar** [comment]
Changed button order.
